title: "OpenNMT Indonesia ↔ Bima"
description: "Proyek OpenNMT Indonesia ↔ Bima. Model NMT untuk Bahasa Indonesia ↔ Bahasa Bima."
url: "https://hazelnutdev.github.io"
baseurl: "/OpenNMT-Indonesia-Bima"

author: 
  name: "HazelDev"
  email: "raposumbawa@gmail.com"

theme: Cayman
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
