title: "OpenNMT Indonesia ke Bima"
description: "OpenNMT  bahasa Indonesia ke Bima. Model NMT untuk Bahasa Indonesia ke Bahasa Bima."
url: "https://hazelnutdev.github.io"
baseurl: "/OpenNMT-Indonesia-Bima"

author: 
  name: "HazelDev"
  email: "raposumbawa@gmail.com"

theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
